- name: Install Mysql
  hosts: sql
  become:yes
  tasks:
  - name: Install Mysql
    ansible.builtin.dnf:
      name: mysql-server
      state: installed
  - name: Start MySQL Service
    ansible.builtin.service:
      name: mysqld
      enabled: yes
      state: started:
  - name: change the default root password in order to start using the database service
    ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1